const EMAIL_RE = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/
const PHONE_RE = /(\+?\d[\d\s().-]{6,}\d)/
const WEBSITE_RE = /((https?:\/\/)?(www\.)?[a-zA-Z0-9-]+\.[a-zA-Z]{2,}(\/\S*)?)/
const COMPANY_HINTS = ['pvt', 'ltd', 'llc', 'inc', 'technologies', 'solutions', 'systems', 'group', 'industries', 'studio', 'studios', 'enterprises', 'corp', 'company', 'co.', 'instruments', 'analytical', 'analytics', 'labs', 'services', 'associates', 'consulting', 'limited', 'incorporated', 'enterprise', 'corporation']
const TITLE_HINTS = ['manager', 'director', 'engineer', 'founder', 'ceo', 'cto', 'coo', 'cfo', 'president', 'head', 'lead', 'consultant', 'designer', 'developer', 'executive', 'officer', 'analyst', 'specialist', 'architect', 'owner', 'partner']
const ADDRESS_KEYWORDS = [
  'plot', 'road', 'rd', 'colony', 'street', 'st', 'building', 'floor', 'block', 'nagar', 'residency', 'apartment', 
  'h.no', 'flat', 'phase', 'sector', 'city', 'state', 'district', 'near', 'opposite', 'behind', 'beside', 
  'highway', 'hwy', 'lane', 'ln', 'cross', 'main', 'industrial', 'area', 'town', 'village', 'taluk', 'bazar', 'bazaar', 
  'chowk', 'marg', 'complex', 'tower', 'towers', 'plaza', 'enclave', 'garden', 'gardens', 'parkway', 'pkwy', 
  'avenue', 'ave', 'drive', 'dr', 'way', 'boulevard', 'blvd', 'court', 'ct', 'place', 'pl', 'terrace', 'ter'
]
function isAddressLine(line) {
  if (/\b\d{5,6}\b/.test(line)) return true
  // Clean punctuation and split into individual words
  const clean = line.replace(/[,./#-]/g, ' ')
  const words = clean.toLowerCase().split(/\s+/)
  if (words.some((word) => ADDRESS_KEYWORDS.includes(word))) return true
  if (words.includes('no') && /\d/.test(line)) return true
  return false
}

function cleanOcrLine(line) {
  let clean = line.trim()
  // Remove leading/trailing symbols, registered marks, and non-alphanumeric noise
  clean = clean.replace(/[\s.,/#!$%^&*;:{}=\-_`~()|?+®¢£¥¤[\]\\]+$/g, '')
  clean = clean.replace(/^[\s.,/#!$%^&*;:{}=\-_`~()|?+®¢£¥¤[\]\\]+/g, '')
  // Remove trailing single-letter noise patterns like "i. z" or "w ="
  clean = clean.replace(/\b[a-zA-Z]\b[\s.:=-]*\b[a-zA-Z]\b[\s.:=-]*$/g, '')
  clean = clean.replace(/\b[a-zA-Z]\b[\s.:=-]*$/g, '')
  // Clean trailing punctuation again if any was exposed
  clean = clean.replace(/[\s.,/#!$%^&*;:{}=\-_`~()|?+®¢£¥¤[\]\\]+$/g, '')
  return clean.trim()
}

function isGarbageLine(line) {
  const clean = line.replace(/\s+/g, '')
  if (clean.length === 0) return true
  // If it looks like a phone number (6+ digits)
  const digitCount = (line.match(/\d/g) || []).length
  if (digitCount >= 6) return false
  // If it looks like an email or website
  // If a line consists entirely of very short alphabetical words (<= 2 characters), it is garbage/noise
  const alphaWords = line.split(/[^a-zA-Z]/).filter((w) => w.length > 0)
  if (alphaWords.length > 0 && alphaWords.every((w) => w.length <= 2)) {
    return true
  }

  // If a line contains mostly single-letter words (words of length 1), it is garbage/noise (e.g. "FLA i . v 3")
  const singleLetterWords = alphaWords.filter((w) => w.length === 1).length
  const multiLetterWords = alphaWords.filter((w) => w.length >= 2).length
  if (singleLetterWords >= 2 && singleLetterWords > multiLetterWords) {
    return true
  }

  // Count letter characters
  const letters = clean.match(/[a-zA-Z]/g) || []
  const letterRatio = letters.length / clean.length
  // If the line has less than 40% letters, it's noise/garbage
  if (letterRatio < 0.40) return true
  // If it contains weird symbols often generated by OCR noise
  if (/[®¢£¥¤|\\_~@#^*]/.test(line)) return true
  // If it has too many symbols/punctuation compared to letters
  const symbolCount = (line.match(/[^a-zA-Z0-9\s]/g) || []).length
  if (symbolCount > letters.length) return true
  return false
}
function isNameCandidate(line) {
  // A name should contain letters, spaces, and optionally dots/hyphens, but no other symbols
  if (/[^a-zA-Z\s.-]/.test(line)) return false
  // A name should have at least 2 words
  const words = line.trim().split(/\s+/)
  if (words.length < 2) return false
  // At least one word should be fully alphabetic and start with a capital letter
  const hasCapitalizedWord = words.some((w) => /^[A-Z][a-z]*$/.test(w) || /^[A-Z]\.$/.test(w))
  if (!hasCapitalizedWord) return false
  // Avoid lines matching address keywords
  const lower = line.toLowerCase()
  if (ADDRESS_KEYWORDS.some((keyword) => lower.includes(keyword))) return false
  return true
}

function extractCompanyFromDomain(emailOrUrl) {
  if (!emailOrUrl) return ''
  let domain = emailOrUrl.toLowerCase()
  // Extract domain part from email
  if (domain.includes('@')) {
    domain = domain.split('@')[1]
  }
  // Extract domain part from website URL
  domain = domain.replace(/^(https?:\/\/)?(www\.)?/i, '')
  domain = domain.split('/')[0]
  domain = domain.split(':')[0]
  // Get name before first TLD
  const parts = domain.split('.')
  let rawName = parts[0]
  if (rawName === 'co' || rawName === 'org' || rawName === 'net' || rawName === 'com') {
    if (parts.length > 1) rawName = parts[1]
  }
  if (!rawName || ['gmail', 'yahoo', 'outlook', 'hotmail', 'mail', 'icloud', 'yandex', 'zoho', 'protonmail', 'proton', 'live'].includes(rawName)) {
    return ''
  }
  // If it starts with "intech", split it into "Intech" and the rest
  let companyName = rawName
  if (rawName.startsWith('intech')) {
    const rest = rawName.slice(6)
    if (rest.length > 0) {
      companyName = 'intech ' + rest
    }
  }
  // Capitalize each word
  return companyName
    .split(/[\s-_]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}
// Tesseract gives back one block of text per card; this splits it into
// lines and assigns each line to the most likely field using regex
// matches for the structured fields (email/phone/website) and keyword
// hints for company/title. The result is meant to be reviewed and
// corrected by the user before saving, not treated as final.
export function parseCardText(rawText) {
  const lines = rawText
    .split('\n')
    .map((l) => cleanOcrLine(l))
    .filter((l) => l.length > 1 && !isGarbageLine(l))
  const fields = {
    'Name': '',
    'Job Title': '',
    'Company': '',
    'Company Name': '',
    'Phone': '',
    'Email': '',
    'Website': '',
    'Address': '',
  }
  const emails = []
  const phones = []
  const websites = []
  const lineStatus = lines.map(() => 'unassigned')
  // 1. Match Emails, Phones, Websites
  lines.forEach((line, idx) => {
    const emailMatch = line.match(EMAIL_RE) || (line.includes('@') && line.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/))
    if (emailMatch) {
      emails.push(emailMatch[0])
      lineStatus[idx] = 'matched'
      return
    }
    const phoneMatch = line.match(PHONE_RE)
    const digitCount = (line.match(/\d/g) || []).length
    if (phoneMatch && digitCount >= 7) {
      phones.push(phoneMatch[0].trim())
      lineStatus[idx] = 'matched'
      return
    }
    const websiteMatch = line.match(WEBSITE_RE)
    if (websiteMatch && /\.(com|in|org|net|io|co|info)\b/i.test(line)) {
      websites.push(websiteMatch[0])
      lineStatus[idx] = 'matched'
      return
    }
  })
  // 2. Classify address vs general lines
  lines.forEach((line, idx) => {
    if (lineStatus[idx] !== 'unassigned') return
    if (isAddressLine(line)) {
      lineStatus[idx] = 'address'
    } else {
      lineStatus[idx] = 'general'
    }
  })
  // 3. Extract Job Title
  let titleIndex = -1
  for (let idx = 0; idx < lines.length; idx++) {
    if (lineStatus[idx] !== 'general') continue
    const lower = lines[idx].toLowerCase()
    if (TITLE_HINTS.some((h) => lower.includes(h))) {
      fields['Job Title'] = lines[idx]
      lineStatus[idx] = 'title'
      titleIndex = idx
      break
    }
  }
  // 4. Extract Company
  let companyIndex = -1
  for (let idx = 0; idx < lines.length; idx++) {
    if (lineStatus[idx] !== 'general') continue
    const lower = lines[idx].toLowerCase()
    if (COMPANY_HINTS.some((h) => lower.includes(h))) {
      fields['Company'] = lines[idx]
      lineStatus[idx] = 'company'
      companyIndex = idx
      break
    }
  }
  // 5. Extract Name (must be a valid name candidate)
  let nameIndex = -1
  for (let idx = 0; idx < lines.length; idx++) {
    if (lineStatus[idx] !== 'general') continue
    if (isNameCandidate(lines[idx])) {
      fields['Name'] = lines[idx]
      lineStatus[idx] = 'name'
      nameIndex = idx
      break
    }
  }
  // Fallback for Name if still empty
  if (!fields['Name']) {
    for (let idx = 0; idx < lines.length; idx++) {
      if (lineStatus[idx] === 'general') {
        const wordCount = lines[idx].split(/\s+/).length
        if (wordCount >= 2) {
          fields['Name'] = lines[idx]
          lineStatus[idx] = 'name'
          nameIndex = idx
          break
        }
      }
    }
  }
  // 6. Merge adjacent unassigned general lines with Company
  if (companyIndex !== -1) {
    if (companyIndex > 0 && lineStatus[companyIndex - 1] === 'general') {
      fields['Company'] = lines[companyIndex - 1] + ' ' + fields['Company']
      lineStatus[companyIndex - 1] = 'company'
    }
    if (companyIndex < lines.length - 1 && lineStatus[companyIndex + 1] === 'general') {
      fields['Company'] = fields['Company'] + ' ' + lines[companyIndex + 1]
      lineStatus[companyIndex + 1] = 'company'
    }
  } else {
    // Check if there are any remaining general lines that are not Name or Title, and pick the first one as Company
    for (let idx = 0; idx < lines.length; idx++) {
      if (lineStatus[idx] === 'general') {
        fields['Company'] = lines[idx]
        lineStatus[idx] = 'company'
        companyIndex = idx
        break
      }
    }
  }
  // Set Company Name
  fields['Company Name'] = fields['Company']
  // Join arrays
  if (phones.length > 0) fields['Phone'] = phones.join(', ')
  if (emails.length > 0) fields['Email'] = emails.join(', ')
  if (websites.length > 0) fields['Website'] = websites.join(', ')
  // 7. Group all address lines + any remaining unassigned general lines as Address
  const addressParts = []
  lines.forEach((line, idx) => {
    if (lineStatus[idx] === 'address' || lineStatus[idx] === 'general') {
      addressParts.push(line)
    }
  })
  if (addressParts.length > 0) {
    fields['Address'] = addressParts.join(', ')
  }
  return fields
}